// API URLs
var URLAPIRanks =					"/apiRanks.html";
var URLAPIRegion =					"/apiRegions.html";
var URLAPIMap =					    "/apiMap.html";
var URLAPITax =						"https://www.cscpro.org/{1}/tax/{2}.jsonp";
// API URLs

// E-SIM URLs
var URLMain = 						"/index.html";
var URLUserStorage = 				"/storage.html";
var URLArticle = 					"/article.html";
var URLNewspaper = 					"/newspaper.html";
var URLEditArticle = 				"/editArticle.html";
var URLMyMU = 						"/myMilitaryUnit.html";
var URLMUMain = 					"/militaryUnit.html?id=";
var URLMUStorage = 					"/militaryUnitStorage.html";
var URLMUMoney = 					"/militaryUnitMoneyAccount.html";
var URLDMUMoney =					"/donateMoneyToMilitaryUnit.html?id=";
var URLMUCompanies = 				"/militaryUnitCompanies.html?id=";
var URLDDonatePlayerProduct = 		"/donateProducts.html?id=";
var URLDonateMUProduct = 			"/donateProductsToMilitaryUnit.html?id=";
var URLCompanies = 					"/companies.html";
var URLCompany = 					"/company.html?id=";
var URLCompanyDetails = 			"/companyWorkResults.html?id=";
var URLCompanyAllWorkers = 			"/companyAllWorkers.html?id=";
var URLCountryEco = 				"/countryEconomyStatistics.html";
var URLBattle = 					"/battle.html?id=";
var URLBattleList = 				"/battles.html";
var URLContracts = 					"/contracts.html";
var URLContract = 					"/contract.html?id=";
var URLMarket = 					"/productMarket.html";
var URLMonetaryMarket = 			"/monetaryMarket.html";
var URLMarketOffers = 				"/citizenMarketOffers.html";
var URLJobMarket =					"/jobMarket.html";
var URLMyShares = 					"/myShares.html";
var URLStockCompany = 				"/stockCompany.html?id=";
var URLStockMM = 					"/stockCompanyMoney.html?id=";
var URLStockProducts = 				"/stockCompanyProducts.html?id=";
var URLStockDonateMoney = 			"/stockCompanyDonateMoney.html?id=";
var URLStockDonateCompany = 		"/stockCompanyDonateCompany.html?id=";
var URLStockLogs = 					"/stockCompanyLogs.html?id=";
var URLTravel = 					"/travel.html";
var URLEquipment =					"/equipment.html";
var URLNewCitizen =					"/newCitizenStatistics.html";
var URLCitizen =					"/CitizenStatistics.html";
var URLSearch =						"/search.html";
var _COUNTRY_URL = 					"/countryEconomyStatistics.html?countryId={1}";
var _MM_C_URL = 					"/monetaryMarket.html?buyerCurrencyId={1}&sellerCurrencyId=0";
var URLBUFF =						"/specialItems.html"
var URLNB =							"/newCitizens.html?countryId=0"
var URLNewRegisteredCitizen =		"/newCitizens.html?countryId=0"
var URLPROFILE = 					"/profile.html"
var URLDMUProduct=					"/donateProductsToMilitaryUnit.html?id=";
var URLDMUComp =					"/donateCompanyToMilitaryUnit.html?id=";
var URLMUMEMB =						"/militaryUnitMembers.html?id="
var URLMUCOMP = 					"/militaryUnitCompanies.html?id="
var URLSO = 						"/serverOverloaded.html"
var URLMUDonations = 				"/militaryUnitDonations.html";
var URLTransactionLog = 			"/transactionLog.html";
var URLSettings = 					"/editCitizen.html?Settings";
var URLShadowGovernment = 			"/editCitizen.html?ShadowGovernment";
// E-SIM URLs

// Image resources
var IMGIRON = 						"http://cdn.e-sim.org/img/productIcons/Iron.png";
var IMGGRAIN = 						"http://cdn.e-sim.org/img/productIcons/Grain.png";
var IMGOIL = 						"http://cdn.e-sim.org/img/productIcons/Oil.png";
var IMGDIAMONDS = 					"http://cdn.e-sim.org/img/productIcons/Diamonds.png";
var IMGWOOD = 						"http://cdn.e-sim.org/img/productIcons/Wood.png";
var IMGSTONE = 						"http://cdn.e-sim.org/img/productIcons/Stone.png";
var IMGWEAPON = 					"http://cdn.e-sim.org/img/productIcons/Weapon.png";
var IMGFOOD = 						"http://cdn.e-sim.org/img/productIcons/Food.png";
var IMGTICKET = 					"http://cdn.e-sim.org/img/productIcons/Ticket.png";
var IMGGIFT = 						"http://cdn.e-sim.org/img/productIcons/Gift.png";
var IMGHOUSE = 						"http://cdn.e-sim.org/img/productIcons/House.png";
var IMGDS = 						"http://cdn.e-sim.org//img/productIcons/Defense%20System.png";
var IMGHOSPITAL = 					"http://cdn.e-sim.org/img/productIcons/Hospital.png";
var IMGESTATE = 					"http://cdn.e-sim.org/img/productIcons/Estate.png";
var IMGQUALITY = 					"http://cdn.e-sim.org/img/productIcons/q";
var IMGEXTENSION = 					".png";
// Image resources

//Image emoticons
var IMGSMILE = "http://cdn.e-sim.org//img/emoticons/smile.png";
var IMGBIGSMILE = "http://cdn.e-sim.org//img/emoticons/bigSmile.png";
var IMGCIACH = "http://cdn.e-sim.org//img/emoticons/ciach.png";
var IMGTONQUE = "http://cdn.e-sim.org//img/emoticons/tongue.png";
var IMGUNHAPPY = "http://cdn.e-sim.org//img/emoticons/unhappy.png";
var IMGEYE = "http://cdn.e-sim.org//img/emoticons/eye.png";
//Image emoticons

//Image pagination buttons
var IMGFIRSTBTN = "https://enterbrain.github.io/img/first.png";
var IMGPREVBTN = "https://enterbrain.github.io/img/prev.png";
var IMGNEXTBTN = "https://enterbrain.github.io/img/next.png";
var IMGLASTBTN = "https://enterbrain.github.io/img/last.png";
//Image pagination buttons

// Others Image
var IMGSTRIPS=						"https://enterbrain.github.io/img/stripes.png";
var IMGGOLD=						"https://enterbrain.github.io/img/gold.png";
var thumbsUp=						"https://enterbrain.github.io/img/e00e.png";
var IMGBUFF =						"https://enterbrain.github.io/img/20px-Intelligence.png";
var IMGSH = 						"https://enterbrain.github.io/img/stock_new_chart_next_graph-20.png";
var IMGTV = 						"https://enterbrain.github.io/img/travels_travel_vector_simple-20.png";
var IMGMM = 						"https://enterbrain.github.io/img/cash_money_dollar_payment_coins_wallet_register.png";
var IMGCT = 						"https://enterbrain.github.io/img/newspaper_edit.png";
var IMGPM = 						"https://enterbrain.github.io/img/Product_basket.png";
var IMGMU = 						"https://enterbrain.github.io/img/Soldier.png";
var IMGPACKAGE = 					"https://enterbrain.github.io/img/icon-gift.gif";
var IMGDOLLAR = 					"https://enterbrain.github.io/img/currency_dollar_pound_money-20.png";
var IMGEQUIPMENT = 					"https://enterbrain.github.io/img/shield_silver.png";
var IMGCOMPANY =					"https://enterbrain.github.io/img/Factory.png";
var IMGONLINE = 					"https://enterbrain.github.io/img/newOnline.png";
var IMGOFFLINE =					"https://enterbrain.github.io/img/newOffline.png";
var IMGPRODBG = 					"https://enterbrain.github.io/img/productIcons/productIconsBackground.png";
var IMGCRITICAL = 					"https://enterbrain.github.io/img/equipmentIcons/criticalHit.png";
var IMGMISS = 						"https://enterbrain.github.io/img/equipmentIcons/reduceMiss.png";
var IMGAVOID = 						"https://enterbrain.github.io/img/equipmentIcons/avoidDamage.png";
var IMGLOAD = 						"https://enterbrain.github.io/img/WorkInProgress.gif";
var noDebuff=						"https://enterbrain.github.io/img/ok.png";
var IMGLOADBAR=						"https://enterbrain.github.io/img/loading_bar.gif";
var IMGDMUMy=						"https://enterbrain.github.io/img/help-donate_32.png"
var IMGDMUPR=						"https://enterbrain.github.io/img/TreasureChest.png";
var IMGDMUCP = 						"https://enterbrain.github.io/img/Factory_company_production.png";
var IMGMUMEMB=						"https://enterbrain.github.io/img/members.gif";
var IMGMUCOMP=						"https://enterbrain.github.io/img/Bldg-RocketFactory.png";
//var IMGBUBL =						"https://enterbrain.github.io/img/education_icons_IF-08-20.png";
var IMGBUBL =						"https://enterbrain.github.io/img/newspaper_edit.png";
// Others Image

//CountyID hash's
var IDByImageCountry = {
	"Poland": 1,
	"Russia": 2,
	"Germany": 3,
	"France": 4,
	"Spain": 5,
	"United-Kingdom": 6,
	"Italy": 7,
	"Hungary": 8,
	"Romania": 9,
	"Bulgaria": 10,
	"Serbia": 11,
	"Croatia": 12,
	"Bosnia-and-Herzegovina": 13,
	"Greece": 14,
	"Republic-of-Macedonia": 15,
	"Ukraine": 16,
	"Sweden": 17,
	"Portugal": 18,
	"Lithuania": 19,
	"Latvia": 20,
	"Slovenia": 21,
	"Turkey": 22,
	"Brazil": 23,
	"Argentina": 24,
	"Mexico": 25,
	"USA": 26,
	"Canada": 27,
	"China": 28,
	"Indonesia": 29,
	"Iran": 30,
	"South-Korea": 31,
	"Taiwan": 32,
	"Israel": 33,
	"India": 34,
	"Australia": 35,
	"Netherlands": 36,
	"Finland": 37,
	"Ireland": 38,
	"Switzerland": 39,
	"Belgium": 40,
	"Pakistan": 41,
	"Malaysia": 42,
	"Norway": 43,
	"Peru": 44,
	"Chile": 45,
	"Colombia": 46,
	"Montenegro": 47,
	"Austria": 48,
	"Slovakia": 49,
	"Denmark": 50,
	"Czech-Republic": 51,
	"Belarus": 52,
	"Estonia": 53,
	"Philippines": 54,
	"Albania": 55,
	"Venezuela": 56,
	"Egypt": 57,
	"Japan": 58,
	"Bangladesh": 59,
	"Vietnam": 60,
	"Yemen": 61,
	"Saudi-Arabia": 62,
	"Thailand": 63,
	"Algeria": 64,
	"Angola": 65,
	"Cameroon": 66,
	"Ivory-Coast": 67,
	"Ethiopia": 68,
	"Ghana": 69,
	"Kenya": 70,
	"Libya": 71,
	"Morocco": 72,
	"Mozambique": 73,
	"Nigeria": 74,
	"Senegal": 75,
	"South-Africa": 76,
	"Sudan": 77,
	"Tanzania": 78,
	"Togo": 79,
	"Tunisia": 80,
	"Uganda": 81,
	"Zambia": 82,
	"Zimbabwe": 83,
	"Botswana": 84,
	"Benin": 85,
	"Burkina-Faso": 86,
	"Congo": 87,
	"Central-African-Republic": 88,
	"DR-of-the-Congo": 89,
	"Eritrea": 90,
	"Gabon": 91,
	"Chad": 92,
	"Niger": 93,
	"Mali": 94,
	"Mauritania": 95,
	"Guinea": 96,
	"Guinea-Bissau": 97,
	"Sierra-Leone": 98,
	"Liberia": 99,
	"Equatorial-Guinea": 100,
	"Namibia": 101,
	"Lesotho": 102,
	"Swaziland": 103,
	"Madagascar": 104,
	"Malawi": 105,
	"Somalia": 106,
	"Djibouti": 107,
	"Rwanda": 108,
	"Burundi": 109,
	"United-Arab-Emirates": 110,
	"Syria": 111,
	"Iraq": 112,
	"Oman": 113,
	"Qatar": 114,
	"Jordan": 115,
	"Western-Sahara": 116,
	"The-Gambia": 117,
	"South-Sudan": 118,
	"Cambodia": 119,
	"Nepal": 120,
	"Bolivia": 121,
	"Ecuador": 122,
	"Paraguay": 123,
	"Uruguay": 124,
	"Honduras": 125,
	"Dominican-Republic": 126,
	"Guatemala": 127,
	"Kazakhstan": 128,
	"Sri-Lanka": 129,
	"Afghanistan": 130,
	"Armenia": 131,
	"Azerbaijan": 132,
	"Georgia": 133,
	"Kyrgyzstan": 134,
	"Laos": 135,
	"Tajikistan": 136,
	"Turkmenistan": 137,
	"Uzbekistan": 138,
	"New-Zealand": 139,
	"Guyana": 140,
	"Suriname": 141,
	"Nicaragua": 142,
	"Panama": 143,
	"Costa-Rica": 144,
	"Mongolia": 145,
	"Papua-New-Guinea": 146,
	"Cuba": 147,
	"Lebanon": 148,
	"Puerto-Rico": 149,
	"Moldova": 150,
	"Jamaica": 151,
	"El-Salvador": 152,
	"Haiti": 153,
	"Bahrain": 154,
	"Kuwait": 155,
	"Cyprus": 156,
	"Belize": 157,
	"Kosovo": 158,
	"East-Timor": 159,
	"Bahamas": 160,
	"Solomon-Islands": 161,
	"Myanmar": 162,
	"North-Korea": 163,
	"Bhutan": 164,
	"Iceland": 165,
	"Vanuatu": 166,
	"Adminland": 777,
}
var ImageCountryByID = {
	1: "Poland",
	2: "Russia",
	3: "Germany",
	4: "France",
	5: "Spain",
	6: "United-Kingdom",
	7: "Italy",
	8: "Hungary",
	9: "Romania",
	10: "Bulgaria",
	11: "Serbia",
	12: "Croatia",
	13: "Bosnia-and-Herzegovina",
	14: "Greece",
	15: "Republic-of-Macedonia",
	16: "Ukraine",
	17: "Sweden",
	18: "Portugal",
	19: "Lithuania",
	20: "Latvia",
	21: "Slovenia",
	22: "Turkey",
	23: "Brazil",
	24: "Argentina",
	25: "Mexico",
	26: "USA",
	27: "Canada",
	28: "China",
	29: "Indonesia",
	30: "Iran",
	31: "South-Korea",
	32: "Taiwan",
	33: "Israel",
	34: "India",
	35: "Australia",
	36: "Netherlands",
	37: "Finland",
	38: "Ireland",
	39: "Switzerland",
	40: "Belgium",
	41: "Pakistan",
	42: "Malaysia",
	43: "Norway",
	44: "Peru",
	45: "Chile",
	46: "Colombia",
	47: "Montenegro",
	48: "Austria",
	49: "Slovakia",
	50: "Denmark",
	51: "Czech-Republic",
	52: "Belarus",
	53: "Estonia",
	54: "Philippines",
	55: "Albania",
	56: "Venezuela",
	57: "Egypt",
	58: "Japan",
	59: "Bangladesh",
	60: "Vietnam",
	61: "Yemen",
	62: "Saudi-Arabia",
	63: "Thailand",
	64: "Algeria",
	65: "Angola",
	66: "Cameroon",
	67: "Ivory-Coast",
	68: "Ethiopia",
	69: "Ghana",
	70: "Kenya",
	71: "Libya",
	72: "Morocco",
	73: "Mozambique",
	74: "Nigeria",
	75: "Senegal",
	76: "South-Africa",
	77: "Sudan",
	78: "Tanzania",
	79: "Togo",
	80: "Tunisia",
	81: "Uganda",
	82: "Zambia",
	83: "Zimbabwe",
	84: "Botswana",
	85: "Benin",
	86: "Burkina-Faso",
	87: "Congo",
	88: "Central-African-Republic",
	89: "DR-of-the-Congo",
	90: "Eritrea",
	91: "Gabon",
	92: "Chad",
	93: "Niger",
	94: "Mali",
	95: "Mauritania",
	96: "Guinea",
	97: "Guinea-Bissau",
	98: "Sierra-Leone",
	99: "Liberia",
	100: "Equatorial-Guinea",
	101: "Namibia",
	102: "Lesotho",
	103: "Swaziland",
	104: "Madagascar",
	105: "Malawi",
	106: "Somalia",
	107: "Djibouti",
	108: "Rwanda",
	109: "Burundi",
	110: "United-Arab-Emirates",
	111: "Syria",
	112: "Iraq",
	113: "Oman",
	114: "Qatar",
	115: "Jordan",
	116: "Western-Sahara",
	117: "The-Gambia",
	118: "South-Sudan",
	119: "Cambodia",
	120: "Nepal",
	121: "Bolivia",
	122: "Ecuador",
	123: "Paraguay",
	124: "Uruguay",
	125: "Honduras",
	126: "Dominican-Republic",
	127: "Guatemala",
	128: "Kazakhstan",
	129: "Sri-Lanka",
	130: "Afghanistan",
	131: "Armenia",
	132: "Azerbaijan",
	133: "Georgia",
	134: "Kyrgyzstan",
	135: "Laos",
	136: "Tajikistan",
	137: "Turkmenistan",
	138: "Uzbekistan",
	139: "New-Zealand",
	140: "Guyana",
	141: "Suriname",
	142: "Nicaragua",
	143: "Panama",
	144: "Costa-Rica",
	145: "Mongolia",
	146: "Papua-New-Guinea",
	147: "Cuba",
	148: "Lebanon",
	149: "Puerto-Rico",
	150: "Moldova",
	151: "Jamaica",
	152: "El-Salvador",
	153: "Haiti",
	154: "Bahrain",
	155: "Kuwait",
	156: "Cyprus",
	157: "Belize",
	158: "Kosovo",
	159: "East-Timor",
	160: "Bahamas",
	161: "Solomon-Islands",
	162: "Myanmar",
	163: "North-Korea",
	164: "Bhutan",
	165: "Iceland",
	166: "Vanuatu",
	777: "Adminland",
}
var CCbyID = {
	1: "PLN",
	2: "RUB",
	3: "DEM",
	4: "FRF",
	5: "ESP",
	6: "GBP",
	7: "ITL",
	8: "HUF",
	9: "RON",
	10: "BGN",
	11: "RSD",
	12: "HRK",
	13: "BAM",
	14: "GRD",
	15: "MKD",
	16: "UAH",
	17: "SEK",
	18: "PTE",
	19: "LTL",
	20: "LVL",
	21: "SIT",
	22: "TRY",
	23: "BRL",
	24: "ARS",
	25: "MXN",
	26: "USD",
	27: "CAD",
	28: "CNY",
	29: "IDR",
	30: "IRR",
	31: "KRW",
	32: "TWD",
	33: "NIS",
	34: "INR",
	35: "AUD",
	36: "NLG",
	37: "FIM",
	38: "IEP",
	39: "CHF",
	40: "BEF",
	41: "PKR",
	42: "MYR",
	43: "NOK",
	44: "PEN",
	45: "CLP",
	46: "COP",
	47: "MEP",
	48: "ATS",
	49: "SKK",
	50: "DKK",
	51: "CZK",
	52: "BYR",
	53: "EEK",
	54: "PHP",
	55: "ALL",
	56: "VEF",
	57: "EGP",
	58: "JPY",
	59: "BDT",
	60: "VND",
	61: "YER",
	62: "SAR",
	63: "THB",
	64: "DZD",
	65: "AOA",
	66: "CM",
	67: "CI",
	68: "ETB",
	69: "GHS",
	70: "KES",
	71: "LYD",
	72: "MAD",
	73: "MZN",
	74: "NGN",
	75: "SN",
	76: "ZAR",
	77: "SDG",
	78: "TZS",
	79: "TG",
	80: "TND",
	81: "UGX",
	82: "ZMW",
	83: "ZWL",
	84: "BWP",
	85: "BJ",
	86: "BF",
	87: "CG",
	88: "CF",
	89: "CDF",
	90: "ERN",
	91: "GA",
	92: "TD",
	93: "NE",
	94: "ML",
	95: "MRO",
	96: "GNF",
	97: "GW",
	98: "SLL",
	99: "LRD",
	100: "GQ",
	101: "NAD",
	102: "LSL",
	103: "SZL",
	104: "MGA",
	105: "MWK",
	106: "SOS",
	107: "DJF",
	108: "RWF",
	109: "BIF",
	110: "AED",
	111: "SYP",
	112: "IQD",
	113: "OMR",
	114: "QAR",
	115: "JOD",
	116: "EH",
	117: "GMD",
	118: "SSP",
	119: "KHR",
	120: "NPR",
	121: "BOB",
	122: "ECD",
	123: "PYG",
	124: "UYU",
	125: "HNL",
	126: "DOP",
	127: "GTQ",
	128: "KZT",
	129: "LKR",
	130: "AFN",
	131: "AMD",
	132: "AZN",
	133: "GEL",
	134: "KGS",
	135: "LAK",
	136: "TJS",
	137: "TMT",
	138: "UZS",
	139: "NZD",
	140: "GYT",
	141: "SRD",
	142: "NIO",
	143: "PAB",
	144: "CRC",
	145: "MNT",
	146: "PGK",
	147: "CUC",
	148: "LBP",
	149: "PRD",
	150: "MDL",
	151: "JMD",
	152: "SVD",
	153: "HTG",
	154: "BHD",
	155: "KWD",
	156: "CY",
	157: "BZD",
	158: "XKD",
	159: "TLD",
	160: "BSD",
	161: "SBD",
	162: "MMK",
	163: "KPW",
	164: "BTN",
	165: "ISK",
	166: "VUT",
	777: "undefined",
}
var IDbyCC = {
	"PLN": 1,
	"RUB": 2,
	"DEM": 3,
	"FRF": 4,
	"ESP": 5,
	"GBP": 6,
	"ITL": 7,
	"HUF": 8,
	"RON": 9,
	"BGN": 10,
	"RSD": 11,
	"HRK": 12,
	"BAM": 13,
	"GRD": 14,
	"MKD": 15,
	"UAH": 16,
	"SEK": 17,
	"PTE": 18,
	"LTL": 19,
	"LVL": 20,
	"SIT": 21,
	"TRY": 22,
	"BRL": 23,
	"ARS": 24,
	"MXN": 25,
	"USD": 26,
	"CAD": 27,
	"CNY": 28,
	"IDR": 29,
	"IRR": 30,
	"KRW": 31,
	"TWD": 32,
	"NIS": 33,
	"INR": 34,
	"AUD": 35,
	"NLG": 36,
	"FIM": 37,
	"IEP": 38,
	"CHF": 39,
	"BEF": 40,
	"PKR": 41,
	"MYR": 42,
	"NOK": 43,
	"PEN": 44,
	"CLP": 45,
	"COP": 46,
	"MEP": 47,
	"ATS": 48,
	"SKK": 49,
	"DKK": 50,
	"CZK": 51,
	"BYR": 52,
	"EEK": 53,
	"PHP": 54,
	"ALL": 55,
	"VEF": 56,
	"EGP": 57,
	"JPY": 58,
	"BDT": 59,
	"VND": 60,
	"YER": 61,
	"SAR": 62,
	"THB": 63,
	"DZD": 64,
	"AOA": 65,
	"CM": 66,
	"CI": 67,
	"ETB": 68,
	"GHS": 69,
	"KES": 70,
	"LYD": 71,
	"MAD": 72,
	"MZN": 73,
	"NGN": 74,
	"SN": 75,
	"ZAR": 76,
	"SDG": 77,
	"TZS": 78,
	"TG": 79,
	"TND": 80,
	"UGX": 81,
	"ZMW": 82,
	"ZWL": 83,
	"BWP": 84,
	"BJ": 85,
	"BF": 86,
	"CG": 87,
	"CF": 88,
	"CDF": 89,
	"ERN": 90,
	"GA": 91,
	"TD": 92,
	"NE": 93,
	"ML": 94,
	"MRO": 95,
	"GNF": 96,
	"GW": 97,
	"SLL": 98,
	"LRD": 99,
	"GQ": 100,
	"NAD": 101,
	"LSL": 102,
	"SZL": 103,
	"MGA": 104,
	"MWK": 105,
	"SOS": 106,
	"DJF": 107,
	"RWF": 108,
	"BIF": 109,
	"AED": 110,
	"SYP": 111,
	"IQD": 112,
	"OMR": 113,
	"QAR": 114,
	"JOD": 115,
	"EH": 116,
	"GMD": 117,
	"SSP": 118,
	"KHR": 119,
	"NPR": 120,
	"BOB": 121,
	"ECD": 122,
	"PYG": 123,
	"UYU": 124,
	"HNL": 125,
	"DOP": 126,
	"GTQ": 127,
	"KZT": 128,
	"LKR": 129,
	"AFN": 130,
	"AMD": 131,
	"AZN": 132,
	"GEL": 133,
	"KGS": 134,
	"LAK": 135,
	"TJS": 136,
	"TMT": 137,
	"UZS": 138,
	"NZD": 139,
	"GYT": 140,
	"SRD": 141,
	"NIO": 142,
	"PAB": 143,
	"CRC": 144,
	"MNT": 145,
	"PGK": 146,
	"CUC": 147,
	"LBP": 148,
	"PRD": 149,
	"MDL": 150,
	"JMD": 151,
	"SVD": 152,
	"HTG": 153,
	"BHD": 154,
	"KWD": 155,
	"CY": 156,
	"BZD": 157,
	"XKD": 158,
	"TLD": 159,
	"BSD": 160,
	"SBD": 161,
	"MMK": 162,
	"KPW": 163,
	"BTN": 164,
	"ISK": 165,
	"VUT": 166,
	"undefined": 777,
}
//CountyID hash's

//TaxID hash's
var TaxNameByID = {
	1: "iron",
	2: "grain",
	3: "oil",
	4: "stone",
	5: "wood",
	6: "diamonds",
	7: "weapon",
	8: "house",
	9: "gift",
	10: "food",
	11: "ticket",
	12: "defense system",
	13: "hospital",
	14: "estate",
}
//TaxID hash's

//Lang hash's
var LangByCC = {
	"United-Kingdom":"English",
	"Albania":"Albanian",
	"Egypt":"Arabic",
	"Armenia":"Armenian",
	"Bangladesh":"Bengali",
	"Bosnia-and-Herzegovina":"Bosnian",
	"Brazil":"Brazilian",
	"Bulgaria":"Bulgarian",
	"China":"Chinese",
	"Croatia":"Croatian",
	"Czech-Republic":"Czech",
	"Netherlands":"Dutch",
	"Estonia":"Estonian",
	"Philippines":"Filipino",
	"France":"French",
	"Georgia":"Georgian",
	"Germany":"German",
	"Greece":"Greek",
	"Israel":"Hebrew",
	"Hungary":"Hungarian",
	"Indonesia":"Indonesian",
	"Italy":"Italian",
	"Latvia":"Latvian",
	"Lithuania":"Lithuanian",
	"Republic-of-Macedonia":"Macedonian",
	"Montenegro":"Montenegrin",
	"Iran":"Persian",
	"Poland":"Polish",
	"Portugal":"Portuguese",
	"Romania":"Romanian",
	"Russia":"Russian",
	"Serbia":"Serbian",
	"Slovakia":"Slovakian",
	"Slovenia":"Slovenian",
	"Spain":"Spanish",
	"Sweden":"Swedish",
	"Taiwan":"TraditionalChinese",
	"Turkey":"Turkish",
	"Ukraine":"Ukrainian",
	"Vietnam":"Vietnamese",
	"Azerbaijan":"Azerbaijani",
	"Denmark":"Danish",
	"Finland":"Finnish",
	"India":"Hindi",
	"Japan":"Japanese",
	"Cambodia":"Khmer",
	"South-Korea":"Korean",
	"Malaysia":"Malaysian",
	"Mongolia":"Mongolian",
	"Nepal":"Nepali",
	"Norway":"Norwegian",
	"Silesia":"Silesian",
	"Thailand":"Thai",
}
var SentManyMotivationsToday = {
	"English":"You have sent too many motivations today",
	"Albanian":"Ju keni dërguar shumë motivime sot",
	"Arabic":"لقد ارسلت تشجيعات اكثر من اللازم اليوم",
	"Armenian":"Այսօրվա համար բավականին մոտիվացիոն փաթեթներ եք ուղարկել",
	"Bengali":"আপনি আজ অনেক বেশি অনুপ্রেরনা দিয়েছেন",
	"Bosnian":"Poslali ste previše motivacija danas",
	"Brazilian":"Você já mandou muitas motivações hoje",
	"Bulgarian":"Изпратихте твърде много мотивации днес",
	"Chinese":"你今天发送的激励过多",
	"Croatian":"Poslali ste previše motivacija danas",
	"Czech":"Dnes si poslal příliš mnoho motivac",
	"Dutch":"Je hebt te veel motivaties gegeven vandaag",
	"Estonian":"Sa oled saatnud täna liiga palju motivatsioone",
	"Filipino":"Nakapagpadala ka na ng napakaraming pagganyak ngayon",
	"French":"Vous avez envoyer trop de paquets de motivations pour aujourd'hui",
	"Georgian":"You have sent too many motivations today",
	"German":"Du kannst für heute keine weiteren Motivationspakete verteilen",
	"Greek":"Έχετε στείλει πάρα πολλές παρακινήσεις σήμερα",
	"Hebrew":"שלחת יותר מדי חבילות מוטיבציה היום",
	"Hungarian":"Túl sok motivációt küldték ma",
	"Indonesian":"Kamu sudah mengirimkan terlalu banyak motivasi hari ini",
	"Italian":"Oggi hai mandato troppi incentivi",
	"Latvian":"Tu šodien esi izsūtījis pārāk daudz motivācijas",
	"Lithuanian":"Jūs jau išsiuntėte per daug motivacijų šiandien",
	"Macedonian":"Имаш испратено премногу мотивации за денес",
	"Montenegrin":"Poslali ste previše motivacija danas",
	"Persian":"شما امروز تقویت زیادی فرستاده اید",
	"Polish":"Wysłałeś dzisiaj zbyt wiele motywacji",
	"Portuguese":"Já mandaste demasiadas motivações hoje",
	"Romanian":"Ai trimis prea multe motivări astăzi",
	"Russian":"Вы отправили слишком много мотиваций сегодня",
	"Serbian":"Послали сте превише мотивација данас",
	"Slovakian":"Dnes si poslal príliš veľa motivácií",
	"Slovenian":"Danes ste poslali preveč motivacij",
	"Spanish":"Has enviado demasiadas motivaciones hoy",
	"Swedish":"Du har skickat för många motivationspaket idag",
	"TraditionalChinese":"您今天已經送出太多激勵品",
	"Turkish":"Bugün çok fazla motivasyon gönderdiniz",
	"Ukrainian":"Ви надто щедрий",
	"Vietnamese":"Bạn gửi quá nhiều động lực hôm nay",
	"Azerbaijani":"You have sent too many motivations today",
	"Danish":"You have sent too many motivations today",
	"Finnish":"You have sent too many motivations today",
	"Hindi":"You have sent too many motivations today",
	"Japanese":"You have sent too many motivations today",
	"Khmer":"You have sent too many motivations today",
	"Korean":"당신은 오늘 너무 많은 선물을 보냈어요",
	"Malaysian":"You have sent too many motivations today",
	"Mongolian":"You have sent too many motivations today",
	"Nepali":"You have sent too many motivations today",
	"Norwegian":"You have sent too many motivations today",
	"Silesian":"You have sent too many motivations today",
	"Thai":"You have sent too many motivations today",
}
var succesfullyMotivated = {
	"English":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Albanian":"Paketa e motivimit është dërguar me sukses! Ju jeni shpërblyer me 1 limit të ushqimit",
	"Arabic":"مجموعة الترحيب تم ارسالها بنجاح. وانت تم مكافئتك بزيادة حد الاكل بنقطة واحدة",
	"Armenian":"Մոտիվացիոն փաթեթն ուղարկվեց. ստացաք մեկ հավելյալ սննդի լիմիտի միավոր",
	"Bengali":"অনুপ্রেরনার প্যাকেজ সফল ভাবে পাঠানো হয়েছে। আপনি 1 খাদ্যসীমা পেয়েছেন",
	"Bosnian":"Motivacijski paket uspješno poslat! Nagrađeni ste 1 limitom hrane",
	"Brazilian":"Pacote de motivação enviado com sucesso! Você foi premiado com +1 no seu limite de comida.",
	"Bulgarian":"Мотивацията беше изпратена успешно! Наградени сте с 1 лимит за храна",
	"Chinese":"成功发送激励包！你得到1个食物上限点",
	"Croatian":"Motivacijski paket uspješno poslat! Nagrađeni ste 1 dodatnim limitom hrane",
	"Czech":"Motivační balíček byl úspěšně poslaný! Byl jsi odměněný 1 limitem na jídlo navíc",
	"Dutch":"Motivatie pakket is succesvol verzonden! Je bent beloond met 1 voedsel limiet punt",
	"Estonian":"Motivatsioonipakett edukalt saadetud! Sinu toidulimiit kasvas +1 võrra",
	"Filipino":"Matagumpay na naipadala ang pakete ng pagganyak! Ikaw ay ginawaran ng 1 puntos sa hangganan sa pagkain",
	"French":"Le pack de motivation a été correctement envoyé ! Vous obtenez 1 point de limite de nourriture",
	"Georgian":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"German":"Motivationspaket wurde erfolgreich gesendet! Du wurdest mit 1 Essenslimitpunkt belohnt",
	"Greek":"Το πακέτο κινήτρου στάλθηκε επιτυχώς! Αυξήθηκε κατά 1 το όριο τροφής.",
	"Hebrew":"חבילת מוטיבציה נשלחה בהצלחה! נוסף לך מקום נוסף לאוכל",
	"Hungarian":"Motivációs csomag sikeresen elküldve! Jutalmad 1 élel korlát pont",
	"Indonesian":"Paket motivasi sudah dikirim dengan sukses! Kamu sudah diberikan 1 limit food tambahan",
	"Italian":"Incentivi inviati con successo! Sei stato ricompensato con 1 limite di Cibo extra",
	"Latvian":"Motivācijas maisiņš bija veiksmīgi aizsūtīts! Jums piešķīra 1 ēdiena limita punktu",
	"Lithuanian":"Motyvacinis paketas sėkmingai išsiųstas. Jūs buvote apdovanotas papildomu 1 maisto limitu",
	"Macedonian":"Мотивациониот пакет е успешно пратен! Беше награден со плус 1 лимит за храна",
	"Montenegrin":"Motivacioni paket poslat uspješno! Bićete nagrađeni sa 1 limitom hrane",
	"Persian":"بسته تقویتی با موفقیت فرستاده شد. یک لیمیت مواد غذایی به شما اعطا شد",
	"Polish":"Pakiet motywacyjny został wysłany. Powiększyliśmy Twój limit jedzenia o 1 punkt.",
	"Portuguese":"O Pacote de motivação foi enviado! Foi adicionado um ponto no limite de comida",
	"Romanian":"Pachetul de motivare a fost trimis cu succes! Ai fost recompensat cu 1 punct de limită la hrană",
	"Russian":"Мотивационный подарок успешно отправлен! Вы удостоены 1 дополнительного лимита на еду",
	"Serbian":"Мотивациони пакет послат успешно. Награђени сте са 1 лимитом хране",
	"Slovakian":"Motivačný balíček bol úspešne odoslaný! Bol si odmenený 1 limitom na jedlo",
	"Slovenian":"Motivacijski paket je poslan uspešno. Nagrajeni ste z 1 točko limita hrane",
	"Spanish":"¡Paquete de motivación enviado con éxito! Obtienes 1 punto en el limite de panes",
	"Swedish":"Motivationspaket sändes! Du har blivit belönad med 1 matpoöng",
	"TraditionalChinese":"激勵包裹發送成功！你得到了一單位的食物上限。",
	"Turkish":"Motivasyon paketi başarılı bir şekilde gönderildi!Fazladan 1 ekmek hakkı ile ödüllendirildiniz",
	"Ukrainian":"Мотиваційну посилку успішно надіслано! Вас винагороджено збільшенням ліміту вживання їжі на 1",
	"Vietnamese":"Hàng động viên đã được gửi thành công! Bạn được thưởng 1 điểm limit ăn bánh",
	"Azerbaijani":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Danish":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Finnish":"Motivaatiopaketti lähetetty onnistuneesti! Sinut on palkittu 1 ruokarajoituspisteellä",
	"Hindi":"प्रेरणा पैकेज सफलतापूर्वक भेजा! आप 1 खाद्य सीमा बिंदु से सम्मानित किया गया है",
	"Japanese":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Khmer":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Korean":"동기부여 패키지가 성공적으로 발송되었습니다! 음식 섭취한도가 1 늘어났습니다.",
	"Malaysian":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Mongolian":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Nepali":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Norwegian":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Silesian":"Motivation package sent succesfully! You've been awarded 1 food limit point",
	"Thai":"Motivation package sent succesfully! You've been awarded 1 food limit point",
}
var YouAlreadySentPackageThisCitizenToday = {
	"English":"You've already sent a package to this citizen today",
	"Russian":'Вы уже отправляли комплект этому гражданину сегодня',
	"German":'Du hast diesem Bürger bereits heute ein Motivationspaket gesendet',
	"Dutch":'Je hebt al een pakket naar deze burger gestuurd vandaag',
	"Czech":'Tomuto občanovi si již dnes poslal balíček',
	"Serbian":'Већ сте послали пакет овом играчу данас',
	"French":"Vous avez déjà envoyé un paquet à ce citoyen aujourd'hui",
}
var CitizenReceivedManyMotivationsToday = {
	"English":'This citizen received too many motivations today',
	"Russian":'Этот гражданин получил слишком много мотиваций сегодня',
}
var CitizenReceivedEveryKindMotivationPackageToday = {
	"English":'This citizen received every kind of motivation package today',
	"Russian":'Этот гражданин получил все виды мотивационных комплектов сегодня',
	"German":'Dieser Bürger hat bereits alle Motivationspakete für heute erhalten',
	"Dutch":'Deze burger heeft elke soort motivatie pakket ontvangen vandaag',
	"Czech":'Tento občan dnes obdržel každý druh motivačního balíku',
	"Serbian":'Играч је примио сваку врсту мотивационог пакета данас',
	"French":"Ce citoyen a reçu toutes les sortes de paquets de motivation pour aujourd'hui",
}
var YouDontHaveEnoughItems = {
	"English":"You don't have enough items",
	"Russian":'У вас не достаточно предметов',
	"German":'Du hast nicht genügend Gegenstände',
	"Dutch":'Je hebt niet genoeg producten',
	"Czech":'Nemáš dostatek předmětů',
	"Serbian":'Немате довољно предмета',
	"French":"Vous n'avez pas assez d'objets",
}
//Lang hash's